-- 코드를 입력하세요
SELECT  RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM    (
            SELECT  FOOD_TYPE, MAX(FAVORITES) FAVORITES
            FROM    REST_INFO
            GROUP BY FOOD_TYPE
        ) FF
    LEFT OUTER JOIN REST_INFO RI
        ON FF.FOOD_TYPE = RI.FOOD_TYPE
            AND FF.FAVORITES = RI.FAVORITES
ORDER BY FF.FOOD_TYPE DESC
