-- 코드를 입력하세요
SELECT  CATEGORY, SUM(SALES) TOTAL_SALES
FROM    BOOK B
        LEFT OUTER JOIN BOOK_SALES BS
            ON B.BOOK_ID = BS.BOOK_ID
WHERE   TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC