-- 코드를 입력하세요
SELECT  B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
        , SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM    BOOK B
    LEFT OUTER JOIN AUTHOR A
        ON B.AUTHOR_ID = A.AUTHOR_ID
    LEFT OUTER JOIN BOOK_SALES BS
        ON B.BOOK_ID = BS.BOOK_ID
WHERE   TO_CHAR(BS.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY B.AUTHOR_ID, B.CATEGORY, A.AUTHOR_NAME
ORDER BY AUTHOR_ID ASC, CATEGORY DESC